### ISSUE TITLE
Example Code - To Do List

### ISSUE THREAD

**Issue by h1cks** [amerkoleci/Vortice.Windows.Samples#1]
Compiling a list of examples using Vortice that should be done various features of DX11/12 in Vortice.

- FMV Demo using Media Foundation
- Sound playback in general
- 3D Sound Demo using XAudio
- Shader Compiling
- Compute Shader Sample

Feel free. I think the appeal of Vortice will also be in the strength of showing how easy it is to get started.

Maybe tag this as document?

**Comment by piotrek1668** [comment]
Hi, the sample collection is very helpful to me. Thank you for your job @amerkoleci and @SuRGeoNix ! It is possible to add another example which show drawing Text on a 3D surface?

**Comment by amerkoleci** [comment]
> Hi, the sample collection is very helpful to me. Thank you for your job @amerkoleci and @SuRGeoNix ! It is possible to add another example which show drawing Text on a 3D surface?

As from README specifications only sponsors can require an example, feel free to submit PR if you have some time to effort :)

**Comment by SuRGeoNix** [comment]
Hi @piotrek1668, you might want to have a look on my old [SharpDX implementation](https://github.com/SuRGeoNix/Flyleaf/blob/release-v2.x/Flyleaf/OSDSurface.cs) which should be easy to convert it to Vortice. It requires DirectWrite. I will try to contribute further with Vortice Samples.
